const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Titulo: 0},
	{resposta1: 0},
	{Mouse: 0},
	{Toque: 0},
	{Sprite: 0},
	{BTNJogar: 0},
	{SairBTN: 0},
	{Navegador: 0},
	{Rectangle: 0},
	{Rectangle2: 0},
	{CreditoBTN: 0},
	{Rectangle3: 0},
	{CRÈDITOS: 0},
	{Rectangle4: 0},
	{CRÈDITOS2: 0},
	{Group: 0},
	{Rectangle5: 0},
	{Rectangle6: 0},
	{Rectangle7: 0},
	{Certa: 0},
	{Errada: 0},
	{QualDasOpçõesAbaixoÉConsideradaUmaSoftSkillEssencialParaResolverConflitosNoTrabalho_: 0},
	{AProgramaçãoEmPython: 0},
	{BComunicaçãoAssertiva: 0},
	{COperaçãoDeMáquinas: 0},
	{DConhecimentoDePlanilha: 0},
	{CColaborarPorUmObjetivoEmComum: 0},
	{DEvitarInteraçõesComColegas: 0},
	{AFazerAsTarefasSozinho: 0},
	{BSeguirOrdensSemQuestionar: 0},
	{OQueMelhorDefineASoftSkilltrabalhoEmEquipe_: 0},
	{AHabilidadeDeSeAdaptarRapidamenteAMudançasNoAmbienteProfissionalÉChamadaDe_: 0},
	{AAdaptabilidade: 0},
	{BLiderançaTécnica: 0},
	{COratória: 0},
	{DGestãoFinanceira: 0},
	{QualAtitudeDemonstraInteligênciaEmocionalNoTrabalho_: 0},
	{CReconhecerEControlarAsPrópriasEmoçõesEmSituaçõesDifíceis: 0},
	{DSempreTentarVencerDiscussões: 0},
	{BReagirImpulsivamenteQuandoContrariado: 0},
	{AIgnorarFeedbacks: 0},
	{OQueCaracterizaASoftSkillDeOrganização_: 0},
	{BManterPrioridadesClarasEGerenciarBemOTempo: 0},
	{AChegarAtrasadoMasCumprirAsTarefas: 0},
	{CFazerMuitasTarefasAoMesmoTempoSemPlanejamento: 0},
	{DDelegarTudoParaOutrasPessoas: 0},
	{OQueCaracterizaASoftSkillDeOrganização_2: 0},
	{Lua: 0},
	{Sprite2: 0},
	{Rectangle8: 0},
	{Group2: 0},
	{Rectangle9: 0},
	{NadouEMorreuNaPraia: 0},
	{Rectangle10: 0},
	{TenteNovamente: 0},
	{Ponto: 0}
];

self.InstanceType = {
	Titulo: class extends self.ISpriteInstance {},
	resposta1: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	Toque: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BTNJogar: class extends self.ISpriteInstance {},
	SairBTN: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	Rectangle: class extends self.ISpriteInstance {},
	Rectangle2: class extends self.ISpriteInstance {},
	CreditoBTN: class extends self.ISpriteInstance {},
	Rectangle3: class extends self.ISpriteInstance {},
	CRÈDITOS: class extends self.ISpriteInstance {},
	Rectangle4: class extends self.ISpriteInstance {},
	CRÈDITOS2: class extends self.ISpriteInstance {},
	Group: class extends self.ISpriteInstance {},
	Rectangle5: class extends self.ISpriteInstance {},
	Rectangle6: class extends self.ISpriteInstance {},
	Rectangle7: class extends self.ISpriteInstance {},
	Certa: class extends self.ISpriteInstance {},
	Errada: class extends self.ISpriteInstance {},
	QualDasOpçõesAbaixoÉConsideradaUmaSoftSkillEssencialParaResolverConflitosNoTrabalho_: class extends self.ISpriteInstance {},
	AProgramaçãoEmPython: class extends self.ISpriteInstance {},
	BComunicaçãoAssertiva: class extends self.ISpriteInstance {},
	COperaçãoDeMáquinas: class extends self.ISpriteInstance {},
	DConhecimentoDePlanilha: class extends self.ISpriteInstance {},
	CColaborarPorUmObjetivoEmComum: class extends self.ISpriteInstance {},
	DEvitarInteraçõesComColegas: class extends self.ISpriteInstance {},
	AFazerAsTarefasSozinho: class extends self.ISpriteInstance {},
	BSeguirOrdensSemQuestionar: class extends self.ISpriteInstance {},
	OQueMelhorDefineASoftSkilltrabalhoEmEquipe_: class extends self.ISpriteInstance {},
	AHabilidadeDeSeAdaptarRapidamenteAMudançasNoAmbienteProfissionalÉChamadaDe_: class extends self.ISpriteInstance {},
	AAdaptabilidade: class extends self.ISpriteInstance {},
	BLiderançaTécnica: class extends self.ISpriteInstance {},
	COratória: class extends self.ISpriteInstance {},
	DGestãoFinanceira: class extends self.ISpriteInstance {},
	QualAtitudeDemonstraInteligênciaEmocionalNoTrabalho_: class extends self.ISpriteInstance {},
	CReconhecerEControlarAsPrópriasEmoçõesEmSituaçõesDifíceis: class extends self.ISpriteInstance {},
	DSempreTentarVencerDiscussões: class extends self.ISpriteInstance {},
	BReagirImpulsivamenteQuandoContrariado: class extends self.ISpriteInstance {},
	AIgnorarFeedbacks: class extends self.ISpriteInstance {},
	OQueCaracterizaASoftSkillDeOrganização_: class extends self.ISpriteInstance {},
	BManterPrioridadesClarasEGerenciarBemOTempo: class extends self.ISpriteInstance {},
	AChegarAtrasadoMasCumprirAsTarefas: class extends self.ISpriteInstance {},
	CFazerMuitasTarefasAoMesmoTempoSemPlanejamento: class extends self.ISpriteInstance {},
	DDelegarTudoParaOutrasPessoas: class extends self.ISpriteInstance {},
	OQueCaracterizaASoftSkillDeOrganização_2: class extends self.ISpriteInstance {},
	Lua: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Rectangle8: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	Rectangle9: class extends self.ISpriteInstance {},
	NadouEMorreuNaPraia: class extends self.ISpriteInstance {},
	Rectangle10: class extends self.ISpriteInstance {},
	TenteNovamente: class extends self.ISpriteInstance {}
}